"""criar tabelas

Revision ID: df4a12e7c02f
Revises: 
Create Date: 2022-11-04 01:14:00.987357

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df4a12e7c02f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(srid=4674, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # op.create_index('idx_edificacao_geom', 'edificacao', ['geom'], unique=False, schema='public', postgresql_using='gist')
    # op.drop_table('spatial_ref_sys')
    # op.drop_table('pointcloud_formats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('pointcloud_formats',
    # sa.Column('pcid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('schema', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(pcid > 0) AND (pcid < 65536)', name='pointcloud_formats_pcid_check'),
    # sa.CheckConstraint('pc_schemaisvalid(schema)', name='pointcloud_formats_schema_check'),
    # sa.PrimaryKeyConstraint('pcid', name='pointcloud_formats_pkey')
    # )
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # op.drop_index('idx_edificacao_geom', table_name='edificacao', schema='public', postgresql_using='gist')
    op.drop_table('edificacao', schema='public')
    # ### end Alembic commands ###
